# Site
repository: edzillion/resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ed Murphy
title: generalist developer
email: edzillion@gmail.com  
website: edzillion.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: edzillion
github_username:  edzillion
stackoverflow_username: "65025"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: edzillion
# linkedin_username: edzillion
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/ed_murphy_avatar.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Ed Murphy and I'm a developer. I have experience of programming (<mark>JS</mark>, <mark>Node</mark>, <mark>TypeScript</mark>, PHP etc), frontend dev (<mark>ReactJS</mark>, <mark>Angular</mark> etc), crypto (Solidity, Truffle/ganache etc) web dev (HTML, CSS etc) server admin (linux, <mark>docker</mark>, <mark>AWS</mark>, Firebase, <mark>Terraform</mark> etc), tools (git, SVN etc) and I am proficient at a host of other design related tools (vector/raster graphics, sound design and arrangement, video editing etc).
  <br>
  <br>
  In terms of soft skills I have experience in <mark>presenting/pitching</mark>, community building, moderating discussions both on and offline, <mark>managing</mark> small teams etc.      
  <br>
  <br>
  I have worked in many different roles and industries. I have returned from a short sabattical full of enthusiasm for the challenges ahead. 

content:
  - title: Recent Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Blood 'n Guts
        link: foundryvtt.com/packages/blood-n-guts
        # link_text: Project Website
        additional_links:
          - title:  edzillion/blood-n-guts
            icon: fab fa-github
            url: github.com/edzillion/blood-n-guts          
        quote: >
          Spray your dungeons with blood!
        description: | # this will include new lines to allow paragraphs
          During the lockdown I got into roleplaying with some friends remotely and was very impressed with Foundry Virtual Table Top. I quickly realised the power of the module system for adding features and developed a few different modules, with this one being the most successful. 
      - layout: top-middle
        title: ghost-backup-s3
        link: github.com/edzillion/ghost-backup-s3
        # link_text: Project Website
        additional_links:
          - title:  edzillion/ghost-backup-s3
            icon: fab fa-github
            url: github.com/edzillion/ghost-backup-s3
          
        quote: >
          Simple docker solution for ghost backup / restore from s3 
        description: | # this will include new lines to allow paragraphs
          I built this tool after using Ghost blogging engine and not being satisfied with the backup/restore options available.


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Circles 
        link: joincircles.net
        # link_text: boringcompany.com
        sub_title: Founder / Full Stack Developer
        caption: 2016 - 2020
        quote: >
          A Basic Income on the Blockchain
        description: | # this will include new lines to allow paragraphs
          I founded and worked for Circles as the main tech person with many roles and responsibilites from frontend design and development (React Native) to internal tools (chat bots, voting systems etc) to backend (both crypto and MERN APIs) and best-practice procedures and processes such as automated building and testing pipelines on AWS.
          As a startup I also undertook pitching and presenting the project at various conferences and meetings, and liaising with developers and partners on various aspects of the project.

      - layout: left
        title: Skyes Enterprises         
        # link_text: boringcompany.com
        sub_title: Player Support Specialist
        caption: 2016 - 2017
        quote: >
          Short-term job
        description: | # this will include new lines to allow paragraphs
          Technical and account support for owners of Sony PlayStation products.

      - layout: left
        title: Simple Lifeforms      
        # link_text: boringcompany.com
        sub_title: Founder / Developer / Game Designer
        caption: 2011 - 2015
        quote: >
          Casual Games / MMO Games / Publishing
        description: | # this will include new lines to allow paragraphs
          Producer / Developer role on project Night Crawlers – also design, art, sound etc. Techs: HTML5, Javascript, NodeJS etc.
          Set up and managed Simple Lifeforms, business development, research, tech development, platform development, marketing, admin, strategy etc.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Leeds University
        caption: 2005 - 2006
        sub_title: Masters in Business Administration <mark>Merit</mark>
        quote: >
          Modules: Project Mgmt, Strategic Mgmt, Marketing, Operations, Managing Change, Economics, HR Mgmt, Accounting, Finance, IP Mgmt, E-Business.
        description: | # this will include new lines to allow paragraphs
          For my dissertation I authored a report on the games industry entitled “Gold Farmers and the Grind: The Changing Business of Persistent State Worlds”.
        
      - layout: left
        title: Bradford University
        caption: 2002 - 2005
        sub_title: BSc Interactive Systems & Video Games Design <mark>1st Class Honours</mark>        
        description: | # this will include new lines to allow paragraphs
          For my major project I created and developed the game Insignia through the role of game designer and technical director. The game was a finalist in the 2005 Dare to Be Digital competition.
          For my individual project I designed, created art, sound assets and coded a J2ME midlet game, based on the arcade classic Gauntlet.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I am a recent migrant to Berlin and I love this city. I like trying my hand at something new and other than my interests in tech I also enjoy:
      - Hiking
      - Arduino / Raspberry Pi SoC Making
      - Live Music & [Deejaying](https://soundcloud.com/edzillion/popular-tracks)
      - Horticulture
      - Petanque 
      - Travel
      - etc.

      From a recent trip to one of the most westerly points in europe.
       
      ![Trees](/images/dursey.webp "Castle Ruins Bere Peninsula")

# Footer
footer_show_references: true
references_title: References on request

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
